version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: university_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: university_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - university_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: university_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/university_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - university_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: university_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - university_network

volumes:
  mysql_data:

networks:
  university_network:
    driver: bridge
